---
- name: Setup Jenkins Master and Agent
  hosts: jenkins-master
  become: yes
  vars:
    jenkins_version: '2.387.1'  # Укажите нужную версию Jenkins
    jenkins_agent_name: 'jenkins-agent'
    remote_user: 'ubuntu'       # Убедитесь, что это правильный пользователь для ваших инстансов AWS
    jenkins_master_url: 'http://{{ ansible_host }}'  # Публичный IP Jenkins мастера
    jenkins_agent_private_ip: "{{ hostvars['jenkins-worker']['ansible_host'] }}"

  tasks:

    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present
   
    
    - name: Install Jenkinscat 
      apt:
        name: jenkins
        state: present
        update_cache: yes
    
    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true    

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: true    

    - name: Configure Nginx as a reverse proxy for Jenkins
      template:
        src: ./nginx/jenkins.conf
        dest: /etc/nginx/sites-available/jenkins.conf
      

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/jenkins.conf
        dest: /etc/nginx/sites-enabled/jenkins.conf
        state: link
      
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


    

    - name: Wait for Jenkins to start
      uri:
        url: "{{ jenkins_master_url }}/login"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    - name: Display Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Print Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password is: {{ jenkins_password.stdout }}"
    
  